[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.141.0"
  DART_SASS_VERSION = "1.77.4"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -D -F"

[context.branch-deploy]
  command = "hugo -D -F"